#!/bin/sh

# Run a command in a shell environment with variables set from
# a gpg-encrypted file. Format of the gpg-encrypted file is VAR_NAME=VAR_VAlUE,
# one per line.

parse_args() {
    set -- "$@"
    ENV_FILE=$1
    shift
    CMD=$@
}

parse_args $@

env $(gpg -q -d $ENV_FILE | xargs ) sh -c "$CMD"
