* Post boot, pre window manager

Easy stuff first. You should have a package manager. Let's get this out of the way.

You might need to install linux kernel headers before installing the rtl88 package. The rtl88 package is for some common Alfa wifi cards. This part might not be necessary.
But I'm putting it first because life is difficult without internet.

#+begin_src
uname -r  # See what version of the kernel you're on.
sudo pacman -Syu linux510-headers yay
yay -Syu rtl88xxau-aircrack-dkms-git
#+end_src

#+BEGIN_SRC
sudo pacman -Syu zsh git emacs ripgrep tmux obs-studio vivaldi yay base-devel dkms xclip rlwrap rxvt-unicode
yay -Syu brave albert-git slack-desktop
#+END_SRC

https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH

You'll probably be doing a lot of terminal work, so symlink the ~.tmux~ stuff and install Oh-My-ZSH.

#+begin_src sh
ln -s $(pwd)/.tmux $HOME
ln -s $(pwd)/.tmux.conf $HOME
#+end_src

And next, you'll be doing a lot of config file editing. Configure Emacs.

Clone Doom to ~.emacs.d~ https://github.com/hlissner/doom-emacs and symlink ~.doom.d~ from this directory. Run the DOOM setup.

If you're frustrated with QWERTY, the steps to switching to Norman are in StumpWM's ~init.lisp~, so if you can hold out long
enough to get the window manager running, you'll be OK. But otherwise, this is what you need:

#+begin_src sh
setxkbmap -variant norman -option lv3:ralt_alt # Or `-variant ,us`
xmodmap -e "keycode 66 = Escape Escape" -e "keycode 9 = Caps_Lock Caps_Lock"
#+end_src

** Login

*** PAM

https://wiki.gnome.org/Projects/GnomeKeyring/Pam

Update /etc/pamd./login to auto start pam_gnome_keyring.

** StumpWM
** LightDM
To get a display manager like LightDM to offer a new window manager like StumpWM, add a .desktop
entry to ~/usr/share/xsessions/~.

*** xinitrcsession-helper
~xinitrc.desktop~ goes in ~/usr/share/xsessions/~

** Terminal theme
~ln -s $(pwd)/.Xresources $HOME/~

* Provisioning
** Applications
*** Firefox
**** Preferences
- disable MRU tab-switching
**** Bitwarden
*** Chrome
*** Tor
*** Tmux
*** Dex
To auto-start xdg .desktop entries
https://github.com/jceb/dex
** Utilities
*** ripgrep
** OpenVPN
*** Generate ovpn config
https://www.privateinternetaccess.com/pages/ovpn-config-generator
*** Enable openvpn systemd client service
https://wiki.archlinux.org/index.php/OpenVPN#systemd_service_configuration
** Doom Emacs
*** Upgrade/update
#+begin_src sh
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

** CommonLisp
** StumpWM
** LightDM
** Tmux
** X11
*** Xresources
